SELECT
FROM
LEAD([FirstName]) OVER(ORDER BY [Id]) AS [Guest Wizzard]
DENSE_RANK() OVER(PARTITION BY [Column] ORDER BY [Column] DESC) AS [NewName]
AVG(), COUNT(), SUM()
WHERE
GROUP BY
ORDER BY
HAVING 

	CASE
		WHEN [Age] BETWEEN 0 AND 10 THEN '[0-10]'
			ELSE 'Something'
	END AS [SomeName]

